version: "3.9"

services:
  app:
    container_name: passwordBot
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
